[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/fr/article/:slug"
  to = "/fr/blog/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/en/article/:slug"
  to = "/en/blog/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/feed.xml"
  to = "/fr/blog/rss.xml"
  status = 301
  force = true

[[redirects]]
  from = "/pricing"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/pricing"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/pricing/success"
  to = "/fr/payment_success"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/pricing/success"
  to = "/en/payment_success"
  status = 302
  force = true